tags:
  - name: Workflows
    description: Endpoints for creating and managing workflow definitions

paths:
  /workflows:
    get:
      tags: [Workflows]
      summary: Get all workflows
      description: Returns all of the workflows that match the filters specified in the query parameters.
      operationId: getAllWorkflows
      parameters:
        - in: query
          name: userId
          schema:
            type: string
            format: uuid
        - in: query
          name: tags
          schema:
            type: string
            description: Comma-separated list of tag names to filter by
      responses:
        "200":
          description: List of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/responses/WorkflowAttributes"

    post:
      tags: [Workflows]
      summary: Create a new workflow
      description: Creates a new workflow using the data specified in the body.
      operationId: createWorkflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  format: uuid
                name:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                metadata:
                  type: object
                rootActionId:
                  type: string
                  format: uuid
              required: [userId]
      responses:
        "200":
          description: Created workflow
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/WorkflowAttributes"

  /workflows/{id}:
    get:
      tags: [Workflows]
      summary: Get a specific workflow
      description: Returns the workflow with the specified ID
      operationId: getWorkflowById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Workflow found
          content:
            application/json:
              schema:
                $ref: "#/components/responses/WorkflowAttributes"
        "404":
          description: Workflow not found

    put:
      tags: [Workflows]
      summary: Update a workflow
      description: Updates the workflow with the specified ID using the data provided in the body
      operationId: updateWorkflow
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                metadata:
                  type: object
                rootActionId:
                  type: string
                  format: uuid
      responses:
        "200":
          description: Workflow updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Updated

    delete:
      tags: [Workflows]
      summary: Delete a workflow
      description: Deletes the workflow with the sepcified ID along with everything uniquely associated with it
      operationId: deleteWorkflow
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Workflow deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Deleted

components:
  responses:
    WorkflowAttributes:
      allOf: 
        - $ref: "./schemas.yaml#/components/schemas/WorkflowAttributes"
        - type: object
          properties:
            tags:
              type: array
              items:
                $ref: "./schemas.yaml#/components/schemas/Tag"
            base_action:
              allOf: 
                - $ref: "./schemas.yaml#/components/schemas/Action"
                - type: object
                - properties:
                    metadata: 
                      type: object
                    permissions: 
                      type: array
                      items:
                        $ref: "./schemas.yaml#/components/schemas/Permission"
            root_action:
              $ref: "./schemas.yaml#/components/schemas/Action"

      required: [id, base_action_id]
