services:
  notify:
    environment:
      SMTP_HOST: smtp4dev
    depends_on:
      - smtp4dev

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - ${SMTP_HOST_UI_PORT}:80 #80 is the universal HTTP port
      - ${SMTP_HOST_SMTP_PORT}:25 #25 is the universal SMTP port