version: "3.8"

services:
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3005:80"
      - "2525:25"
  
  notify:
    build: .
    environment:
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_FROM=se_svc_apps@rit.edu
      - PORT=4000
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "4000:4000"
    depends_on:
      - smtp4dev
  
  mysql:
    image: mysql:8.0
    container_name: notification_service_mysql
    environment:
      MYSQL_ROOT_PASSWORD: newPassword
      MYSQL_DATABASE: notification_service
    ports:
      - '3307:3306'
    volumes:
      - rit_mysql_data:/var/lib/mysql
        
volumes:
  rit_mysql_data:

