version: "3.8"
services:
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3005:80"
      - "2525:25"
  notify:
    build: .
    environment:
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_FROM=se_svc_apps@rit.edu
      - PORT=4000
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL:-mysql://root:password@host.docker.internal:3308/rit_notifications}
    ports:
      - "4000:4000"
    depends_on:
      - smtp4dev
