import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import ThemeRegistry from "ThemeRegistry";
import { UserProvider } from "utils/user-context/page";
import ToastProvider from "@components/ToastProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SCOOP Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <AppRouterCacheProvider>
    <ThemeRegistry>
    <UserProvider>
      {children}
      <ToastProvider />
    </UserProvider>
    </ThemeRegistry>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}
