import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/styles.css";
import ThemeRegistry from "@/styles/ThemeRegistry";
import UserProvider from "@/context/AuthContext";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                style={{
                    // Some inline styles force weird margin and padding on the body,
                    // so these override those
                    margin: 0,
                    padding: 0,
                }}
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
            >
                <UserProvider>
                    <ThemeRegistry>
                        <main className="grow">{children}</main>
                        <Footer />
                    </ThemeRegistry>
                </UserProvider>
            </body>
        </html>
    );
}
