services:
  frontend:
    build:
    # Point to the dev dockerfile, which runs next dev instead of building and starting the app.
      dockerfile: apps/ta-portal/ui/Dockerfile.dev
      args:
        # If NODE_ENV is DEV, uses testing login, otherwise uses prod login
        NEXT_PUBLIC_NODE_ENV: "DEV"
        # A url being prepended to paths means that fetch requests are made absolute:
        # fetch(https://localhost:3300/ta-portal-api/db/Users) connects to https://localhost:3300/ta-portal-api/db/Users
        NEXT_PUBLIC_BACKEND_URL: "https://localhost:3300"

  backend:
    build:
      args:
        # domain url of the frontend. Used in main.js to defined allowed orgins of requests.
        FRONTEND_URL: "https://localhost:3000"
    environment:
      # Is used mainly in errorHandlerTest.js and featureFlags.js.
      NODE_ENV: "DEV"
      # URL used to access the notification service
      NOTIFICATION_SERVICE_URL: "htp://localhost:4000"
    