services:
  frontend:
    build:
      # Point to the prod dockerfile, which builds and starts the app instead of running next dev
      dockerfile: apps/ta-portal/ui/Dockerfile.prod
      args:
        # If NODE_ENV is DEV, uses testing login, otherwise uses prod login
        NEXT_PUBLIC_NODE_ENV: "DEV"
        # No url being prepended to paths means that fetch requests are made relativly:
        # fetch(/ta-portal-api/db/Users) connects to current-domain.com/ta-portal-api/db/Users
        NEXT_PUBLIC_BACKEND_URL: ""

  backend:
    build:
      args:
        # domain url of the frontend. Used in main.js to defined allowed orgins of requests.
        FRONTEND_URL: "http://apps-staging.se.rit.edu"
    environment:
      # Is used mainly in errorHandlerTest.js and featureFlags.js.
      NODE_ENV: "production"