name: cmt

services:
  frontend:
    build:
      context: ../..
      dockerfile: apps/cmt/frontend/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    image: frontend:${TAG:-latest}

  backend:
    build:
      context: ../..
      dockerfile: apps/cmt/backend/Dockerfile
    image: backend:${TAG:-latest}