name: cmt

services:
  frontend:
    build:
      context: ../..
      dockerfile: apps/cmt/frontend/Dockerfile
    image: cmt-frontend:${TAG:-latest}

  backend:
    build:
      context: ../..
      dockerfile: apps/cmt/backend/Dockerfile
    image: cmt-backend:${TAG:-latest}