.read table_sql/semester_group.sql
.read table_sql/users.sql
.read table_sql/teams.sql
.read table_sql/projects.sql
.read table_sql/student_mentorship.sql
.read table_sql/actions.sql
.read table_sql/action_log.sql
.read table_sql/time_log.sql
.read table_sql/archive.sql
.read table_sql/page_html.sql