name: Monorepo CI/CD

on:
  push:
    branches:
      - main
      - dev
      - '*-dev'
      - '*-cicd-testing'
  pull_request:
    branches:
      - main
      - dev
      - '*-dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup & Cache Dependencies
    runs-on: ubuntu-latest
    outputs:
      nx-base: ${{ steps.set-base.outputs.base }}
      nx-head: ${{ steps.set-head.outputs.head }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set base and head commits for Nx
        id: set-base
        run: echo "base=origin/main" >> $GITHUB_OUTPUT

      - name: Set head commit
        id: set-head
        run: echo "head=HEAD" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Nx output
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-cache-${{ github.sha }}

          
  lint:
    name: Lint Affected Projects
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Run Affected Lint
        run: npx nx affected:lint
  
  build:
    name: Build Affected Projects
    needs: [setup, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./
      - run: CI=false npx nx affected:build --base=${{ needs.setup.outputs.nx-base }} --head=${{ needs.setup.outputs.nx-head }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  deploy:
    name: Deploy Affected Apps
    if: github.ref == 'refs/heads/main' || endsWith(github.ref, '-dev') || github.ref == 'refs/heads/dev' || endsWith(github.ref, '-cicd-testing')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CMT_DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "DEPLOY_KEY=$HOME/.ssh/deploy_key" >> $GITHUB_ENV

      - name: Add staging server to known_hosts
        run: |
          ssh-keyscan -H apps-staging.se.rit.edu >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm ci
      - name: deploy
        run: nx affected -t deploy